WebBanHangOnline/Controllers/ReviewController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHangOnline.Models;
using WebBanHangOnline.Models.EF;

namespace WebBanHangOnline.Controllers
{
    [Authorize]
    public class ReviewController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        // GET: Review
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult _Review(int productId)
        {
            ViewBag.ProductId = productId;
            var item = new ReviewProduct();
            if (User.Identity.IsAuthenticated)
            {
                var userStore = new UserStore<ApplicationUser>(new ApplicationDbContext());
                var userManager = new UserManager<ApplicationUser>(userStore);
                var user = userManager.FindByName(User.Identity.Name);
                if (user != null)
                {
                    item.Email = user.Email;
                    item.FullName = user.FullName;
                    item.UserName = user.UserName;
                }
                return PartialView(item);
            }
            return PartialView();
        }

        public ActionResult LichSuDonHang()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userStore = new UserStore<ApplicationUser>(new ApplicationDbContext());
                var userManager = new UserManager<ApplicationUser>(userStore);
                var user = userManager.FindByName(User.Identity.Name);
                var items = _db.Orders.Where(x=>x.CustomerId==user.Id).ToList();
                return PartialView(items);
            }
           
            return PartialView();
        }

        [AllowAnonymous]
        public ActionResult _Load_Review(int productId)
        {
            var item = _db.Reviews.Where(x => x.ProductId == productId).OrderByDescending(x => x.Id).ToList();
            ViewBag.Count = item.Count;
            return PartialView(item);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult PostReview(ReviewProduct req)
        {
            if (ModelState.IsValid)
            {
                req.CreatedDate = DateTime.Now;
                _db.Reviews.Add(req);
                _db.SaveChanges();
                return Json(new { Success = true });
            }
            return Json(new { Success = false });
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

WebBanHangOnline/Views/Review/LichSuDonHang.cshtml
@model IEnumerable<WebBanHangOnline.Models.EF.Order>
@if (Model != null)
{
    var i = 1;
    <h2>Lich Su Mua Hang</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>STT</td>
                <td>Mã DH</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@i</td>
                    <td>@item.Code</td>
                </tr>
                i++;
            }
        </tbody>
    </table>
}

WebBanHangOnline/Views/Review/_Load_Review.cshtml
@model IEnumerable<WebBanHangOnline.Models.EF.ReviewProduct>
<div class="tab_title reviews_title">
    <h4>Reviews (@ViewBag.Count)</h4>
</div>

<!-- User Review -->
@if (Model != null && Model.Any())
{
    foreach (var item in Model)
    {
        <div class="user_review_container d-flex flex-column flex-sm-row">
            <div class="user">
                <div class="user_pic"></div>
                <div class="user_rating">
                    <ul class="star_rating">
                        @Html.Raw(WebBanHangOnline.Common.Common.HtmlRate(item.Rate))
                    </ul>
                </div>
            </div>
            <div class="review">
                <div class="review_date">@item.CreatedDate.ToString("dd MM yyyy")</div>
                <div class="user_name">@item.FullName</div>
                <p>@item.Content</p>
            </div>
        </div>

        <!-- User Review -->

        @*<div class="user_review_container d-flex flex-column flex-sm-row">
            <div class="user">
                <div class="user_pic"></div>
                <div class="user_rating">
                    <ul class="star_rating">
                        @Html.Raw(WebBanHangOnline.Common.Common.HtmlRate(item.Rate))
                    </ul>
                </div>
            </div>
            <div class="review">
                <div class="review_date">@item.CreatedDate.ToString("dd MM yyyy")</div>
                <div class="user_name">@item.FullName</div>
                <p>@item.Content</p>
            </div>
        </div>*@

    }

}

WebBanHangOnline/Views/Review/_Review.cshtml
@model WebBanHangOnline.Models.EF.ReviewProduct


<div class="add_review">
    @using (Ajax.BeginForm("PostReview", "Review", new AjaxOptions
    {
        HttpMethod = "POST",
        UpdateTargetId = "load_review",
        OnSuccess = "OnSuccessRE",
        OnFailure = "OnFailureRE",
        OnBegin = "OnBeginRE"

    }, new { @Id = "review_form" }))
    {
        <script>
            function OnBeginRE() {
                $('#review_submit').attr("disabled", "disabled");
                $('#load_send').html('<h2>Đang gửi....</h2>');
            }
            function OnSuccessRE(res) {
                debugger;
                if (res.Success) {
                    $("#review_form")[0].reset();
                }
            }
        </script>
        @Html.AntiForgeryToken()@*<form id="review_form" action="post">*@
        <div>
            <h1>Add Review</h1>
            @Html.TextBoxFor(x => x.FullName, new { @class = "form_input input_name", @placeholder = "Name*", @id = "review_name" })
            @Html.TextBoxFor(x => x.Email, new { @class = "form_input input_email", @placeholder = "Email*", @id = "review_email" })
            @Html.HiddenFor(x => x.UserName)
            @Html.HiddenFor(x => x.ProductId, new { @Value = ViewBag.ProductId })
            <input type="text" id="txtRate" name="Rate" value="4" style="visibility:hidden;"/>
            @*<input id="review_name" class="form_input input_name" type="text" name="name" placeholder="Name*" required="required" data-error="Name is required.">*@
            @*<input id="review_email" class="form_input input_email" type="email" name="email" placeholder="Email*" required="required" data-error="Valid email is required.">*@
        </div>
        <div>
            <h1>Your Rating:</h1>
            <ul class="user_star_rating">
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star" aria-hidden="true"></i></li>
                <li><i class="fa fa-star-o" aria-hidden="true"></i></li>
            </ul>
            @Html.TextAreaFor(x => x.Content, new { @class = "input_review", @rows = "4", @placeholder = "Your Review" })
            @*<textarea id="review_message" class="input_review" name="message" placeholder="Your Review" rows="4" required data-error="Please, leave us a review."></textarea>*@
        </div>
        <div class="text-left text-sm-right">
            <button id="review_submit" type="submit" class="red_button review_submit_btn trans_300" value="Submit">submit</button>
        </div>
    }
</div>